api:
  base_url: "https://api.deepseek.com/v1"
  api_key: "DEEPSEEK_API_KEY" # DEEPSEEK_API_KEY/OPENAI_API_KEY/paste your API key here
  model_name: "deepseek-v4-flash"
data:
  accu_path: "data/accu.txt"
  law_path: "data/law.txt"
test:
  seed: 42
  max_samples: 100
  test_file: "data/final_all_data/first_stage/test.json"
  result_dir: "results"
retriever:
  index_root: "data/index_hierarchical"
  retrieval_model: "uer/sbert-base-chinese-nli"
  elements_weight: 0.7
  fact_weight: 0.3
  top_k: 3
index:
  embedding_model: "uer/sbert-base-chinese-nli"
